name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: blazor-publish
        path: ./publish

    # Step to get the release ID of the existing release
    - name: Get existing release ID
      id: get_release
      run: |
        REPO="sohn-io/nump"  # Replace with your repo name
        TAG="0.1"  # Replace with the tag of the release you want to upload to
        RESPONSE=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "https://api.github.com/repos/$REPO/releases/tags/$TAG")
        echo "Release response: $RESPONSE"
        RELEASE_ID=$(echo $RESPONSE | jq -r .id)
        UPLOAD_URL=$(echo $RESPONSE | jq -r .upload_url | sed 's/{?name,label}//')
        echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV
        echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV

    # Step to upload the artifact to the existing release
    - name: Upload Windows Artifact to Existing Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: ./bin/nump.windows-amd64.zip
        asset_name: nump.windows-amd64.zip
        asset_content_type: application/zip
